<?php

/**
 * @file
 * Custom behavior for Barnard Digital Collections.
 */

/**
 * Implements hook_init().
 *
 * Disable caching for the front page only.
 */
function bc_islandora_init() {
  if (drupal_is_front_page()) {
    drupal_page_is_cacheable(FALSE);
  }
}

/**
 * Implements hook_permission().
 */
function bc_islandora_permission() {
  return array(
    'administer bc_islandora' => array(
      'title' => t('Administer Barnard Islandora'),
      'description' => t('Perform administrative tasks for Barnard Islandora.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function bc_islandora_menu() {
  $items = array();
  $items['admin/islandora/bc_config'] = array(
    'title' => 'Configure Barnard Islandora',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bc_islandora_config'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer bc_islandora'),
  );
  $items['admin/islandora/bc_metadata'] = array(
    'title' => 'Update Barnard Metadata',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bc_islandora_metadata_form'),
    'file' => 'metadata.inc',
    'file path' => drupal_get_path('module', 'bc_islandora') . '/includes',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('administer bc_islandora'),
  );
  $items['islandora/object/%islandora_object/download_transcript'] = array(
    'page callback' => 'bc_islandora_download_transcript',
    'page arguments' => array(2),
    'type' => MENU_CALLBACK,
    'access callback' => 'islandora_object_access',
    'access arguments' => array(ISLANDORA_VIEW_OBJECTS, 2),
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function bc_islandora_theme($existing, $type, $theme, $path) {
  return array(
    'bc_islandora_newspaper_issue_navigator' => array(
      'variables' => array(
        'object' => NULL,
        'start_page' => 1,
      ),
      'file' => 'includes/theme.inc',
    ),
    'bc_islandora_newspaper_page_controls' => array(
      'variables' => array(
        'object' => NULL,
      ),
      'file' => 'includes/theme.inc',
    ),
    'bc_islandora_breadcrumb' => array(
      'variables' => array(
        'breadcrumb' => array(),
      ),
      'file' => 'includes/theme.inc',
    ),
  );
}

/**
 * Implements hook_form().
 */
function bc_islandora_config($form, &$form_state) {
  // TODO others to add?
  $form['bc_islandora_newspaper_pid'] = array(
    '#type' => 'textfield',
    '#title' => t('Newspaper collection pid'),
    '#default_value' => variable_get('bc_islandora_newspaper_pid', ''),
  );
  $form['bc_islandora_pubs_pid'] = array(
    '#type' => 'textfield',
    '#title' => t('Student Publications collection pid'),
    '#default_value' => variable_get('bc_islandora_pubs_pid', 'islandora:1022'),
  );
  $form['bc_islandora_manuscripts_pid'] = array(
    '#type' => 'textfield',
    '#title' => t('Manuscripts collection pid'),
    '#default_value' => variable_get('bc_islandora_manuscripts_pid', 'islandora:manuscriptCollection'),
  );
  $form['bc_solr_date_facet_format'] = array(
    '#type' => 'textfield',
    '#title' => t('PHP date format that Solr should use for the date facet.'),
    '#default_value' => variable_get('bc_solr_date_facet_format', 'Y/m/d'),
    '#description' => t('<strong>Only accepts: day, month, and year format characters of d/j m/n Y/y.</strong> <br /><a target=_new href="http://php.net/manual/en/function.date.php#refsect1-function.date-parameters">PHP Date Format documentation.</a> <br />Format preview: @format', array('@format' => date(variable_get('bc_solr_date_facet_format', 'Y/m/d')))),
  );
  $form['bc_islandora_hide_datepicker'] = array(
    '#type' => 'checkbox',
    '#title' => t('Hide date picker?'),
    '#default_value' => variable_get('bc_islandora_hide_datepicker', TRUE),
    '#description' => t('Whether to hide the date picker when faceting search results by date range.'),
  );
  return system_settings_form($form);
}

/**
 * Makes a "transcript" (concatenated page OCR) available for download.
 *
 * @see islandora_download_datastream()
 */
function bc_islandora_download_transcript($islandora_pid) {
  module_load_include('inc', 'islandora_paged_content', 'includes/utilities');
  module_load_include('inc', 'bc_islandora', 'includes/utilities');

  if ($object = islandora_object_load($islandora_pid)) {
    $object_cid = _bc_islandora_get_transcript_cid($object);

    // If this object's transcript has been cached, use the cached version.
    if ($cached_ocr = cache_get($object_cid)) {
      $object_ocr = $cached_ocr->data;
    }
    // Otherwise, generate a new transcript and cache it.
    else {
      $object_ocr = _bc_islandora_generate_transcript($object);
      cache_set($object_cid, $object_ocr);
    }

    // Download the transcript as a text file.
    header('Content-type: text/plain');
    header("Content-Disposition: attachment; filename=\"{$object_cid}.txt\"");
    print $object_ocr;
    exit();
  }

  return drupal_not_found();
}

/**
 * Implements hook_form_alter().
 */
function bc_islandora_form_islandora_paged_content_manage_page_edit_ocr_form_alter(&$form, &$form_state, $form_id) {
  $form['#submit'][] = '_bc_islandora_update_transcript_cache';
}

/**
 * Submit handler for page OCR form.
 */
function _bc_islandora_update_transcript_cache($form, &$form_state) {
  module_load_include('inc', 'bc_islandora', 'includes/utilities');
  $object = $form_state['object'];
  $object_cid = _bc_islandora_get_transcript_cid($object);
  cache_set($object_cid, _bc_islandora_generate_transcript($object));
}

/**
 * Implements hook_form_alter().
 */
function bc_islandora_form_islandora_solr_date_filter_form_alter(&$form, &$form_state) {

  // Get rid of datepicker js if we have the correct setting.
  if (variable_get('bc_islandora_hide_datepicker', FALSE)) {
    unset($form['#attached']);
  }

  // Fetch our date facet_format.
  $query_params = drupal_get_query_parameters();
  !empty($query_params['date_format']) ? $facet_format = $query_params['date_format'] : $facet_format = variable_get('bc_solr_date_facet_format', 'Y/m/d');

  // Update the format helper text.
  $form['date_filter']['date_filter']['#markup'] = '<div class="description">(Valid formats: YYYY, YYYY/MM, YYYY/MM/DD)</div>';

  // Remove titles and add placeholder text instead.
  unset($form['date_filter']['date_filter_from']['#title']);
  unset($form['date_filter']['date_filter_to']['#title']);
  $form['date_filter']['date_filter_from']['#attributes']['placeholder'] = 'Start';
  $form['date_filter']['date_filter_from']['#suffix'] = '<span id="between-dates">to </span>';
  $form['date_filter']['date_filter_to']['#attributes']['placeholder'] = 'End';

  // Change "Filter" to "Apply".
  $form['date_filter']['date_filter_submit']['#value'] = 'Apply';

  // Add a handler to modify the date_filter_to to the latest date possible
  // based on current input.
  array_unshift($form['#submit'], 'bc_islandora_form_islandora_solr_date_filter_form_submit');

  // Do not add anything to blank fields. Leave this function.
  if (!$form['date_filter']['date_filter_from']['#default_value'] && !$form['date_filter']['date_filter_to']['#default_value']) {
    return;
  }

  // Modify the current form to use our facet_format.
  $date_from = new DateTime($form['date_filter']['date_filter_from']['#default_value']);
  $date_to = new DateTime($form['date_filter']['date_filter_to']['#default_value']);
  $form['date_filter']['date_filter_from']['#default_value'] = $date_from->format($facet_format);
  $form['date_filter']['date_filter_to']['#default_value'] = $date_to->format($facet_format);
}

/**
 * When using a facet_format, appends the "oldest date" as the date_filter_to.
 */
function bc_islandora_form_islandora_solr_date_filter_form_submit(&$form, &$form_state) {
  module_load_include('inc', 'bc_islandora', 'includes/utilities');
  global $_islandora_solr_queryclass;

  $form_date_from = $form_state['values']['date_filter']['date_filter_from'];
  $form_date_to = $form_state['values']['date_filter']['date_filter_to'];

  $_islandora_solr_queryclass->internalSolrParams['date_format'] = bc_islandora_get_date_format($form_date_from, $form_date_to);
  $form_state['values']['date_filter']['date_filter_to'] .= bc_islandora_get_latest_possible_date($form_date_to);
}

/**
 * Implements hook_form_alter().
 *
 * Removes title from Islandora Solr's "Simple Search Box"
 *
 * @see: https://github.com/BarnardArchives/digitalcollections.barnard.edu/issues/15
 */
function bc_islandora_form_islandora_solr_simple_search_form_alter(&$form, &$form_state) {
  $form['simple']['islandora_simple_search_query']['#title'] = '<none>';
}

/**
 * Because we want the list display, but not the word "default" in the name.
 *
 * Credit: https://github.com/uml-digitalinitiatives/manidora/blob/7.x/manidora.module#L865-L879.
 */
function bc_islandora_islandora_solr_primary_display() {
  return array(
    'bcislandora_list' => array(
      'name' => t('List'),
      'module' => 'islandora_solr',
      'file' => 'includes/results.inc',
      'class' => "IslandoraSolrResults",
      'function' => "displayResults",
      'description' => t("A simple output."),
    ),
  );
}

/*
 * Meta-data related modifications.
 */

/**
 * Implements hook_islandora_datastream_alter().
 *
 * @see metadata.inc
 */
function bc_islandora_islandora_datastream_alter($object, $datastream, &$context) {
  if ($object['MODS'] && $datastream->id == 'MODS' && $context['action'] == 'ingest') {
    module_load_include('inc', 'bc_islandora', 'includes/metadata');
    _bc_islandora_generate_primary_dislpay_url($object, TRUE);
  }
}

/**
 * Implements hook_barnard_islandora_metadata_functions().
 */
function bc_islandora_barnard_islandora_metadata_functions() {
  return array(
    'bc_primary_display_url' => array(
      'name' => t('Add: Primary Display URL to MODs'),
      'module' => 'bc_islandora',
      'file' => 'metadata.inc',
      'function' => '_bc_islandora_generate_primary_dislpay_url',
      'description' => t("Generates mods:location/mods:url[usage='primary display']."),
    ),
    'bc_primary_' => array(
      'name' => t('Remove: HOCR Doctype.'),
      'module' => 'bc_islandora',
      'file' => 'metadata.inc',
      'function' => '_bc_islandora_remove_HOCR_doctype',
      'description' => t("Removes the HOCR HTML Doctype delcaration."),
    ),
  );
}
